development:
  clients:
    default:
      uri: "<%= Rails.application.credentials.mongodb[:uri] %>"
      options:
        server_selection_timeout: 5

production:
  clients:
    default:
      uri: "<%= Rails.application.credentials.mongodb[:uri] %>"
      options:
        server_selection_timeout: 5
